### ISSUE TITLE
exception during startup

### ISSUE THREAD

**Issue by fauno** [coderkun/mcg#9]
if i run `./mcgGtk.py` from a checkout i get this error

```text
avahi error
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 516, in _work
    method(*args)
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 232, in _connect
    self._sock = self._connect_socket(host, port)
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 261, in _connect_socket
    raise ConnectionException("connection failed: {}".format(error))
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 26, in __init__
    super(MPDException, self).__init__(self._parse_error(error))
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 31, in _parse_error
    self._error = int(parts.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

i also had to copy the data dir into the mcg and the setup.py is missing a comma before the url field :)

**Comment by fauno** [comment]
btw i see the gui but everything is grayed out

**Comment by coderkun** [comment]
I saw the “Avahi” error, too, some time ago and will investigate.

I usually run the application from the root folder with the following command (this way the “data” folder will be found correctly):
`./mcg/mcgGtk.py`

**Comment by coderkun** [comment]
Comma fixed with 91bd91c.

**Comment by fauno** [comment]
fwiw i did a little debugging and the error is a connectiong failure,
but the parts regex can't parse this message:

connection failed: [Errno 111] Connection refused

(which is odd since mpd is working and i can control it perfectly with
ncmpcpp)

-- 
 D

**Comment by coderkun** [comment]
> but the parts regex can't parse this message

That’s right, I will improve the regex and add some checks later or tomorrow.

> i did a little debugging and the error is a connectiong failure

Is your MPD server running on the default port (6600)?

**Comment by fauno** [comment]
coderkun <notifications@github.com> writes:
>> i did a little debugging and the error is a connectiong failure
>
> Is your MPD server running on the default port (6600)?

yes, it has a password but you can use it readonly without it, even
`telnet localhost 6600` works


-- 
:D

**Comment by coderkun** [comment]
> it has a password but you can use it readonly without it, even `telnet localhost 6600` works

So if you disable the password on the server or if you enter the password on the client side, is it working then?

I think I have to test the whole password functionality. Thanks for testing btw!

**Comment by fauno** [comment]
coderkun <notifications@github.com> writes:
> So if you disable the password on the server or if you enter the password on the client side, is it working then?

nope, it's the same error

> I think I have to test the whole password functionality. Thanks for testing btw!

np :)

-- 
:D

**Comment by coderkun** [comment]
I think we have multiple problems here:

1. “wrong” regex: fixed by 0ac3b3f
1. connection cannot be established
1. (unsupported) read-only mode: #10

**Comment by coderkun** [comment]
If MPD requires authorization for “control” command but allows read-only commands, the application throws (gracefully handled) errors for “control” commands but connects fine.

Can you confirm this? Is it starting for you fine as well?

**Comment by coderkun** [comment]
This issue has inspired #10.

**Comment by fauno** [comment]
coderkun <notifications@github.com> writes:

> If MPD requires authorization for “control” command but allows read-only commands, the application throws (gracefully handled) errors for “control” commands but connects fine.
>
> Can you confirm this? Is it starting for you fine as well?

even with this on mpd.conf i always get a connection refused error when
i click the connect button after configuring it for localhost:6600 and
no password

    default_permissions  "read,add,control,admin"
    password             "xxxx@read,add,control,admin"



-- 
 D

**Comment by coderkun** [comment]
Do you get any additional information on the command line?

To enable debug logging you can set the log level on line 118 of mcgGtk.py:

        logging.getLogger(mcg.__name__).setLevel(logging.DEBUG)

**Comment by fauno** [comment]
@± master ~/Projects/mcg ./mcg/mcgGtk.py
avahi error
connect
add action '_connect' (('localhost', 6600, None))
start worker
next action: (<bound method Client._connect of <mcg.Client object at 0xb383be0c>>, ('localhost',
6600, None))
work: '_connect'
connecting to host 'localhost', port 6600
worker started
connection failed: [Errno 111] Conexión rehusada
Traceback (most recent call last):
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 519, in _work
    method(*args)
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 235, in _connect
    self._sock = self._connect_socket(host, port)
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 264, in _connect_socket
    raise ConnectionException("connection failed: {}".format(error))
mcg.ConnectionException: connection failed: [Errno 111] Conexión rehusada
disconnected
action done
@± master ~/Projects/mcg telnet localhost 6600
Trying ::1...
Connection failed: Conexión rehusada
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.19.0
^]
telnet> quit
Connection closed.

**Comment by coderkun** [comment]
This doesn’t look like an error in the application itself. The connection can just not be established somehow.

**Comment by fauno** [comment]
got it! changing host to 127.0.0.1 worked!  apparently mcg solves
localhost to ipv6, but mpd only listens on ipv4

now i see the gui but everything is empty, though i see some data being
retrieved from mpd.  the error seems to be that it fails to load a file
whose track number is 'A1':

invalid literal for int() with base 10: 'A1'
Traceback (most recent call last):
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 519, in _work
    method(*args)
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 403, in _load_albums
    track = MCGTrack(mpdTrack['artist'], mpdTrack['title'], trackNumber, trackTime, trackDate, mp
dTrack['file'])
  File "/home/fauno/Projects/mcg/mcg/mcg.py", line 819, in __init__
    track = int(track)
ValueError: invalid literal for int() with base 10: 'A1'

**Comment by coderkun** [comment]
I see but this is done by Python and not by the application itself.

“A1” in track numbers is a different issue: #12
